@startuml MySchedule
title MySchedule クラス図
skinparam dpi 150

class Application {
  - _appUser: AppUser

  - get appUser(): AppUser
  - set appUser(value: AppUser): void

  + run(): void
  - initializeFirebase(): void
  - redirect(): void
  - createPage(): void
}

class FirebaseInitializer {
  + initialize(): void
}

class AppUser {
}

class PageUtils {
  + createPage(): void
}

Application --> FirebaseInitializer
Application --> AppUser
Application --> PageUtils

@enduml