@startuml MySchedule
title MySchedule クラス図
skinparam dpi 150

class Application {
  - _appUser: AppUser

  - get appUser(): AppUser
  - set appUser(value: AppUser)

  + run(): void
  - initializeFirebase(): void
  - redirect(): void
  - createPage(): void
}

class FirebaseInitializer {
  - readonly defaultConfig: object
  - _firebaseConfig: object
  - _app:FirebaseApp
  - _analytics:Analytics

  - get firebaseConfig(): object
  - set firebaseConfig(value: object)
  - get app(): FirebaseApp
  - set app(value: FirebaseApp)
  - get analytics(): Analytics
  - set analytics(value: Analytics)

  + constructor(config?: object)

  + initialize(): void
}

class AppUser {
    - _uid: string
    - _userInfo: UserInfo

    - get uid(): string
    - set uid(uid: string): void
    - get userInfo(): UserInfo
    - set userInfo(userInfo: UserInfo): void

    + setUserInfo(email: string, password: string): void
    + async assignUserInfo(): Promise<void>
    + async signUp(redirectLink?: string): Promise<void>
    + async signIn(redirectLink?: string): Promise<void>
    + async signOut(redirectLink?: string): Promise<void>
    + resetEmail(email: string): void
    + async sendEmail(subject: string, text: string): Promise<void>
    + async getAuthState(): Promise<User | null>
    + async redirect():Promise<void>
}

class PageUtils {
  + static getPageType(): PageType
  - static getQuery(paramName: string): string | null
  + static matchQuery(paramName: string, value: string | null)
  + createPage(): void
}

Application --> FirebaseInitializer
Application --> AppUser
Application --> PageUtils

@enduml