MySchedule/.github/workflows/deploy.yaml
@@ -33,14 +33,26 @@ jobs:
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: "npm"

      - name: Install dependency
        run: npm ci

      - name: Build
        run: npm run build

          # Viteのbuildコマンド出力先ディレクトリを指定
          path: './dist'
